### ISSUE TITLE
Switch to Astropy convolution for S+C finder

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#10]
Astropy convolution functions should handle NaN's better than the SciPy functions currently used in the S+C finder. Tests will be needed to establish whether the Astropy functions can actually be implemented successfully in the S+C finder.

**Comment by SoFiA-Admin** [comment]
From what I remember, we switched from SciPy to AstroPy a long time ago, so this issue can probably be closed.
