### ISSUE TITLE
Mask and subcubes

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#100]
SoFiA allows users to provide an input mask to be applied to the input cube. SoFiA also allows users to process just a section of the input cube (called subcube). This issue is about how to handle cases where a user provides an input mask and requests to process a subcube.

Option 1. Assume that the input mask has the same shape of the input cube, and apply the same subcube selection to the input mask. This is the current behaviour (implemented in https://github.com/SoFiA-Admin/SoFiA/commit/d84cf7779e16f967374a00e606fe3e503b12e69a).

Option 2. Assume that the input mask has the same shape as the selected subcube. (This was the past behaviour, although the implementation was actually incorrect.)

I would favour the former option. If a user has made a mask from a subcube and wants to use it as input mask they will have to pad it with zeros.

Please comment.

**Comment by paoloserra** [comment]
Something to keep in mind for this discussion: when processing a subcube and producing an output mask, the mask has the same shape of the subcube, not of the original, larger cube. So this would be a point in favour of option 2 above.

However, if we decide to go for option 2 (i.e., the input mask is taken as it is, with no subcube selection applied to it) we need to add some checks that the input mask shape and WCS grid agrees with that of the selected subcube.

**Comment by SoFiA-Admin** [comment]
Interesting question. I would initially have thought that having the input mask of the same size as the input cube (irrespective of what sub-cube is chosen) and output mask the same size as the output cube would be the natural way to go. However, this poses a problem if the output mask is to used as input again.

Could we maybe allow both full-sized and subcube-sized masks as input? We could simply implement a check to verify that the specified input mask is either consistent with the full cube or with the selected sub-cube. This could be complicated in practice, unless we don't care about the WCS and simply ensure that the dimensionality and size in pixels matches (it would then be up to the use to ensure that the correct part of the cube is represented by the mask).

**Comment by paoloserra** [comment]
Yes after discussions with Nadine we agreed to allow both options. I will implement that. Some WCS checks should be simple too. At least we could require that the CRVAL's are the same.

**Comment by paoloserra** [comment]
I have implemented the change. See https://github.com/SoFiA-Admin/SoFiA/commit/1fa9a9573794f22d023e172c818c3ec6328f8f09 and please test.

**Comment by SoFiA-Admin** [comment]
This has been fixed and can be closed.
