### ISSUE TITLE
WCS conversion problem

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#103]
When running SoFiA on a 4-dimensional cube with Stokes I as the 4ᵗʰ dimension, source finding works fine, but WCS conversion will fail with the following message:

    --- SoFiA: Adding WCS position to catalogue ---
    WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (3) [astropy.wcs.wcs]
    WARNING: WCS conversion of parameters failed.

Apparently, the WCS information is provided for all 4 dimensions, while the data it needs to be applied to are only 3-dimensional.

**Comment by bwinkel** [comment]
When you instantiate the wcs object with the header, you can use the naxis-keyword to use only a subspace of the axes, e.g.

```python
from astropy import wcs
header = [...]
my_wcs = wcs.WCS(header, naxis=[wcs.WCSSUB_CELESTIAL, wcs.WCSSUB_SPECTRAL])
```
After this, you should be able use the transformation functions with 3 dimensional data.

**Comment by SoFiA-Admin** [comment]
Thank you for the tip. I will try to implement this fix as soon as I find the time.

**Comment by SoFiA-Admin** [comment]
I implemented the proposed change, and WCS conversion now appears to work fine on 4-D data cubes. This issue can now be closed.
