### ISSUE TITLE
Improvements to reliability module

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#105]
Following feedback from an active SoFiA user, some improvements have been suggested to SoFiA’s reliability module. The main suggestion is to not simply rely on the local ratio of positive and negative sources to determine reliability, but to also exclude certain continuous volumes in parameter space, similar to fixed thresholds for each parameter, but in the form of an <i>N</i>-dimensional **curved surface** in parameter space rather than a simple box-shaped exclusion region. The best way of defining such a surface will need to be explored, and its shape and location may depend on the actual parameter settings within SoFiA.

Other, minor suggestions include to review the actual parameters used by the reliability module and their correlations and to provide a three-dimensional visualisation of the distribution of detections in parameter space.

**Comment by SoFiA-Admin** [comment]
A table of correlation coefficients of linker output parameters is attached. The colour varies from blue (fully correlated) to green (uncorrelated) and red (fully anti-correlated). The results are based on running SoFiA on 1 GB of ASKAP data with just noise, but no visible HI emission in it. The S+C threshold was set to 3 sigma with a merging length of [1, 1, 1] and a minimum source size requirement of [5, 5, 4].

![analysis](https://user-images.githubusercontent.com/6572706/48301403-8aac6e00-e4e5-11e8-8770-dc888774e69b.png)

**Comment by paoloserra** [comment]
We've run a few tests and it seems that working in parSpace ["snr_sum","snr_mean","snr_max"] is good and much better than, e.g., ["snr_sum","npix",snr_max"] (see matrix above). We may want to switch to this parameter space by default after some further testing.

We've also implemented a threshold on integrated SNR = "snr_sum"/sqrt("npix") as an additional filter of the catalogue of detections. This threshold replaces the previous, arbitrary threshold on "snr_sum". See https://github.com/SoFiA-Admin/SoFiA/commit/590699f2870c495966f98fcfb2cbb7d1251ce695 .

Will keep this issue open as the reliability module can probably be improved in a few other ways still.

**Comment by paoloserra** [comment]
@SoFiA-Admin Can we add the integrated SNR threshold to the GUI? If so, I would recommend spelling out what quantity we are using for this: Sum(pixels)/noise/sqrt(Nv

**Comment by SoFiA-Admin** [comment]
The fMin parameter is now available in the GUI. Please test and let me know if you encounter any problems.

**Comment by paoloserra** [comment]
Thanks a lot @SoFiA-Admin 

I've seen that you've included a detailed description of this parameter in the GUI's help. However, I'm a little worried that nobody will bother reading it because they'll think they know what SNR is. And they'll be annoyed to find that, e.g., SNR=7 retains numerous false detections.

Shouldn't we maybe refrain from calling this option "SNR cutoff"? How about "minimum Sum(flux)/noise/sqrt(Npix)"?

**Comment by SoFiA-Admin** [comment]
We could do that. Just to clarify, are we actually calculating

 ∑ <var>S</var><sub><var>i</var></sub> / (σ <var>N</var><sup>1/2</sup>)

or

 ∑ <var>S</var><sub><var>i</var></sub> / <var>N</var><sup>1/2</sup>,

i.e. are we dividing by the RMS, either implicitly or explicitlt, or not?

**Comment by paoloserra** [comment]
We divide by the RMS in https://github.com/SoFiA-Admin/SoFiA/blob/e3d413c4f84fa29174e474d77cb306687f3979f2/sofia_pipeline.py#L448 .

**Comment by SoFiA-Admin** [comment]
Thanks, @paoloserra, I updated the GUI and user manual accordingly, now using “∑&thinsp;<var>S</var><sub><var>i</var></sub>&thinsp;/&thinsp;(σ&thinsp;<var>N</var><sup>1/2</sup>) cut” as the new label in the GUI.

**Comment by SoFiA-Admin** [comment]
All of this has been implemented and appears to be working very well, so I will close this issue now. Feel free to reopen if any problem arises.

**Comment by SoFiA-Admin** [comment]
Update: As agreed, the default parameter space has now been changed to `["snr_sum", "snr_mean", "snr_max"]` in the SoFiA default parameter file to replace the highly correlated `n_pix` parameter with `snr_mean`. All tests seem to indicate that the new parameter space is at least as good as, if not superior to, the old one.
