### ISSUE TITLE
CUNIT4 keyword required

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#108]
A user recently reported the following error when trying to read in a data cube into SoFiA:

    Traceback (most recent call last):
      File "~/SoFiA-master/sofia_pipeline.py", line 207, in <module>
    Loading cube: ~/G351.417.6035_LL_CUBE.FITS
    
        np_Cube, dict_Header, mask, subcube = import_data.read_data(Parameters['steps']['doSubcube'],**Parameters['import'])
      File "~/SoFiA-master/build/lib.macosx-10.11-x86_64-2.7/sofia/import_data.py", line 125, in read_data
        del(dict_Header['cunit4'])
      File "~/env/lib/python2.7/site-packages/astropy/io/fits/header.py",  line 228, in __delitem__
        raise KeyError("Keyword '%s' not found." % key)
    KeyError: "Keyword 'CUNIT4' not found."
    Pipeline failed with exit code 1.

The problem seems to be that for some unknown reason `astropy` requires a `CUNIT4` keyword for the fourth axis (which is Stokes LL). As for SoFiA the `CUNIT4` doesn’t matter at all, we may want to look into how to prevent this error message from popping up in the future.

In principal, `CUNITn` keywords are optional in FITS, and default units are defined in the FITS standard in case `CUNITn` is missing. We may in general want to test SoFiA’s behaviour in situations where `CUNITn` keywords are missing from the header and ensure that their absence doesn’t break the pipeline.

**Comment by ngiese** [comment]
The error message says, that we are trying to delete the 'CUNIT4' keyword, which cannot be found. This is an error on our side, because we are trying to delete keywords without checking if they are actually present. This should be changed in the import module (lines 121-126), which could be done e.g. like this:
  for key in ['ctype4','crpix4','crval4',...]:
    if key in dict_Header:
      del dict_Header[key]
If you want, I can change those lines.

**Comment by SoFiA-Admin** [comment]
Thanks for offering to fix this problem. When I added the `CTYPE4` and `CUNIT4` keywords to the list of things to be deleted (see #106), I was wondering about exactly this point, because I noticed that there was no check to ensure that these keywords actually existed. At the time I assumed that this had been done intentionally and `del` would simply ignore non-existent keywords. But it looks like that’s not the case, so please go ahead and implement the proposed change.

**Comment by ngiese** [comment]
I changed import_data.py accordingly.

**Comment by SoFiA-Admin** [comment]
Thank you! I will let the affected user know, so he can install the latest version.
