### ISSUE TITLE
Remove checks for astropy module

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#110]
Since we require astropy for the import module, it is not optional any more. Checks for the module (e.g. lines 22-25 in import_module.py, 113-116 in wcs_coordinates.py) and resulting parts of code could therefore be removed. Any objections?

**Comment by SoFiA-Admin** [comment]
I agree that those can be removed, since Astropy is a requirement anyway.

**Comment by ngiese** [comment]
Done.
