### ISSUE TITLE
Problems during SoFIA tutorial

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#116]
Here is a list of a few problems encountered by participants of the SoFiA tutorial at the PHISCC meeting in Pune:

* WCS calculation at end of pipeline run resulted in segmentation fault on two users’ machines.
* <s>Results differ (3 vs. 5 detections) for users on Mac and Linux.</s>

**Comment by vdhulst** [comment]
Re "Results differ (3 vs. 5 detections) for users on Mac and Linux." This has been resolved and appeared to be the result of having noise scaling in z off versus on.

**Comment by paoloserra** [comment]
Will close for now. Please open again if there is more detailed information on this problem.
