### ISSUE TITLE
Issue with masks of 4-D cubes

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#117]
SoFiA currently strips any 4th dimension from the header when generating detection masks. However, this leads to problems in some software, such as CASA, which expects the shape of a mask to be identical to that of the image cube.

We should therefore leave the dimensionality of the cube untouched when creating masks, even if the highest dimension is trivial, to ensure that the masks can be used in other software that isn’t smart enough to check for trivial header dimensions.

**Comment by SoFiA-Admin** [comment]
Just a quick update, I already changed the code such that all header keywords related to the 4th axis are now retained when reading in the cube (4d4cc4b92587b9e9fecbe6ca4ebe076bc1d969ec). When checking the header right after reading the file, everything looks fine. `NAXIS` is set to 4 and all `C....4` keywords are present.

The only remaining problem is that after writing the mask cube to disc, some process changes the value of the `NAXIS` keyword to 3 again and removes the `NAXIS4` keyword entirely, while leaving the `CTYPE4`, `CRVAL4` etc. keywords untouched. This problem may need to be addressed by deliberately adding a 4th dimension to the data array again prior to writing the mask cube, whenever the `NAXIS` keyword is found to be 4.

**Comment by paoloserra** [comment]
https://github.com/SoFiA-Admin/SoFiA/commit/052e4ddd0cbe3b269b507fdc1267ea2be96603aa
