### ISSUE TITLE
Develop error handling module

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#119]
There are still several instances across the SoFiA code where user input is not checked for correctness and validity. I just discovered and fixed a few of those in the pipeline (2b743f76e73c8ac443e7a407325a3313a17f32df), but it would be desirable to write a dedicated error handling module in Python that could be used for systematic input checks and printing of helpful error messages, as discussed at the last telecon. The module could be set up such that it can be called from within any other module and will check all relevant data automatically. We already have a [wiki page](https://github.com/SoFiA-Admin/SoFiA/wiki/List-of-potential-errors-to-be-handled) that contains a (still incomplete) list of things to check for.

**Comment by paoloserra** [comment]
Do we still need this? Error handling has improved significantly throughout the code.

**Comment by SoFiA-Admin** [comment]
Indeed, we should close this, as error handling is slightly better now that it was originally. In addition, we should focus on having proper handling of errors and warnings is SoFiA 2 instead.
