### ISSUE TITLE
Parameterisation and determinism problems

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#122]
There appears to be a rather bizarre determinism issue with parameterisation results coming from SoFiA. In the example considered here, a small cube is pre-filtered by a Gaussian of width 3 in all three dimensions, then the wavelet filter is applied with a threshold of 5<var>σ</var>, and finally the threshold finder is run on the output with a relative threshold of 4<var>σ</var>, where <var>σ</var> is determined via the standard deviation. Note that these choices are not particularly meaningful, but this is irrelevant for the following discussion. 6 sources are detected by SoFiA in total, most of which are due to noise. In several cases the fitting of ellipses or measurement of <var>w</var><sub>m50</sub> will fail. This is not unexpected, as the detections are due to noise, so the fit can be expected to fail. However, the following problem is observed:

* When SoFiA is run on the same cube by different users, the sources for which ellipse fitting or <var>w</var><sub>m50</sub> measurement fails are not the same, but vary from user to user, even though all users run the same SoFiA installation in the same virtual machine with the same parameter file and on the same input data cube.

I currently have no clue as to where this problem could possibly arise. I will run a few more tests and take a closer look at the code to see if there is any obvious explanation for this strange behaviour.

**Comment by paoloserra** [comment]
Can we get the relevant dataset and parameter file? We should try to reproduce this problem (it was a whole ago) and get to the bottom of it.

**Comment by SoFiA-Admin** [comment]
As we have absolutely no clue as to why this occurred in the first place, and no way of reproducing this problem, we will be left with no other choice but to close this issue as “won’t fix”.
