### ISSUE TITLE
Introduce the possibility to use a cube for flagging

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#123]
User feedback suggests that the possibility to use a cube for flagging is useful. For the implementation we should take the following into account:

1) What are the typical voxel values in a flag cube?
2) In which part of the pipeline should this new feature be implemented? Since we need to import the flag cube, it makes sense to include it in the import module. However, there is a separate flagging module to flag, which does not contain a lot of code.

My suggestion is to implement it in the import module and move the flagging module as it is right now into the preprocessing module.

**Comment by SoFiA-Admin** [comment]
Regarding the first question, I checked the latest FITS standard again (version 3.0 from July 2008) to investigate the recommended handling of blanked pixels. According to the standard:

* For `BITPIX = -32` or `-64` (floating-point data) the IEEE value of `NaN` (not a number) should be used to represent an undefined value.
* For positive values of `BITPIX` (integer data) the `BLANK` keyword is used to define the integer value that represents pixels of undefined physical value.

In the latter case, if the `BSCALE` and `BZERO` keywords are present, `BLANK` must be the raw integer value, not its transformed physical value. For more information see Section 4.4.2.5 of the [FITS Standard](https://fits.gsfc.nasa.gov/fits_standard.html).

**Comment by ngiese** [comment]
The option to use a cube for flagging has been implemented (c43ca04). I have committed two parameter change requests.

**Comment by paoloserra** [comment]
Thanks!!!!!
