### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#126]
I started converting SoFiA’s Python code such that it would run in both Python 2.7 and 3.X. The main issues addressed so far are:

* Inclusion of parentheses around arguments of `print` commands.
* Consistent indentation with tabulators, as Python 3 refuses to run code with mixed space/tab indentation.
* Minor modifications to a few `import` commands.

After these changes, the Python code of SoFiA seems to run fine under both Python versions (2.7.6 and 3.4.3) on my machine. However, there are two outstanding issues still to be addressed:

1. The results of integer divisions are treated differently in Python 2 and 3 (conversion to float vs. rounding), so all divisions need to be checked and reimplemented such that the expected result will be achieved in all Python versions.

2. When running SoFiA with Python 3, there is currently an error message related to the wavelet finder:
   ```
   Traceback (most recent call last):
     File "/SoFiA/git/sofia_pipeline.py", line 19, in <module>
       from sofia import wavelet_finder
     File "/SoFiA/git/build/lib.linux-x86_64-2.7/sofia/wavelet_finder.py", line 5, in <module>
       from sofia import wavelet as wv
   ImportError: /SoFiA/git/build/lib.linux-x86_64-2.7/sofia/wavelet.so: undefined symbol: _Py_ZeroStruct
   ```
  
   The problem appears to be that the shared object code compiled from the C code produced by Cython somehow doesn’t work. I tried recythonizing the code with Cython 3 and then recompiling, but that didn’t solve the problem.

Any comments on these issues, in particular the second one, would be most welcome.

**Comment by bwinkel** [comment]
That's a nice initiative!

A year ago, I've also migrated most of my software to Python 3, so I have some tips that might be useful:

1) If you aim to support Py 2 and 3 at the same time, it is best to put the following imports at the top of each file (even Cython files):
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
```

2) With the "division" import from __future__, you can then use the "//" operator in Py 2, as well. And indeed one should replace all integer division operations to make use of the new operator.

3) In Cython, you can use the directive "# cython: language_level=3" if you want Py 3 support. If that doesn't help already, I can have a further look into it later. By-the-way, we also have a stand-alone package of the wavelet code. @lfloeer, could we upload it to GitHub? Maybe it's useful to have it as external package (and only import it if user needs it)?

**Comment by bwinkel** [comment]
I cannot help myself to say the following: you may seriously want to consider to use spaces (4 per indentation level) instead of Tabs, as almost every other Python package. Many people (like me) will have their editors configured to auto-replace tabs with spaces on file opening. Can lead to a lot of extra-work if you receive pull requests.

**Comment by paoloserra** [comment]
I agree with @bwinkel on tabs

**Comment by SoFiA-Admin** [comment]
### Update on Python 3 migration

First of all, thanks to @bwinkel for these useful tips. I added the `#cython: language_level=3` directive and successfully recompiled `wavelet.c` such that it would run under Python&nbsp;3. The main reason for why this was not the case originally is that Cython&nbsp;3 does not overwrite the `wavelet.so` file in the `built` directory, but instead creates a new file called `wavelet.cpython-34m.so`. Hence, I had to create a symbolic link to that file, as otherwise the old Python&nbsp;2.7 version of `wavelet.so` would be called.

Next, I got a few more error messages regarding Python&nbsp;2.7-specific code that needed to be changed. This mainly had to do with how **dictionaries** are accessed, in particular the use of **iterators** which got changed in Python&nbsp;3.

With these changes I finally managed for the first time to execute the pipeline using Python&nbsp;3, getting exactly the same 3&nbsp;detections that I would have expected from the Python&nbsp;2.7 run, so that’s good news.

There are, however, a few issues still remaining that I haven’t yet investigated any further:

* I have not checked for **integer divisions** yet, so that’s still work to be done.

* The **parameterisation** module crashes with the following message:
  
  ```
  File "/SoFiA/git/sofia_pipeline.py", line 555, in <module>
    np_Cube, mask, objects, catParNames, catParFormt, catParUnits = parametrisation.parametrise(np_Cube, mask, objects, catParNames, catParFormt, catParUnits, Parameters, dunits)
  File "/SoFiA/git/build.3.4/lib.linux-x86_64-3.4/sofia/parametrisation.py", line 90, in parametrise
    'x': cp.PyMeasurement('x', obj[cathead == 'x_geo'], 0., ''),
  File "cparametrizer.pyx", line 145, in cparametrizer.PyMeasurement.__cinit__ (src/parametrizer/cparametrizer.cpp:3349)
  File "cparametrizer.pyx", line 168, in cparametrizer.PyMeasurement.setM (src/parametrizer/cparametrizer.cpp:3606)
  File "cparametrizer.pyx", line 180, in cparametrizer.PyMeasurement.setName (src/parametrizer/cparametrizer.cpp:3823)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_ (src/parametrizer/cparametrizer.cpp:13333)
  TypeError: expected bytes, str found
  ```

* When turning off parameterisation, I get all the way to the end up to the point where **WCS coordinates** are extracted and added to the catalogue. At that point there is a memory access error:
  
  ```
  --- SoFiA: Adding WCS position to catalogue
  *** Error in `python3': free(): corrupted unsorted chunks: 0x0000000002a41a80 ***
  Abort (core dumped)
  ```

Overall, my impression is that Python&nbsp;3 compatibility is achievable without too much effort. However, as Cython code would have to be re-cythonized to the correct language version and appears to create different output filenames depending on which language version is being used, we may have to offer **two separate SoFiA packages** for download, one for Python&nbsp;2.7 and another one optimised for Python&nbsp;3.X. It should be fairly straightforward, though, to turn the default 2.7 package (with the compatibility measures discussed above implemented) into a 3.X package, so there should be no need to maintain two entirely separate code bases.

**Comment by bwinkel** [comment]
Hi @SoFiA-Admin,

I just tried to build the package with both, Py 2+3, and in the "build" directory I get two sub-folders containing the following:

lib.linux-x86_64-2.7/sofia/cparametrizer.so
lib.linux-x86_64-2.7/sofia/wavelet.so
lib.linux-x86_64-3.5/sofia/cparametrizer.cpython-35m-x86_64-linux-gnu.so
lib.linux-x86_64-3.5/sofia/wavelet.cpython-35m-x86_64-linux-gnu.so

When I go into either of "lib.linux-x86_64-2.7" or "lib.linux-x86_64-3.5", start the appropriate Python CLI and run
```python
from sofia import cparametrizer
from sofia import wavelet
```
it works. Can you give some details about your problem? Especially, I don't figure your comment on having to make a symbolic link. (In Py 3 the interpreter will "ignore" the "cpython-35m-x86_64-linux-gnu" part of the module name.)

**Comment by SoFiA-Admin** [comment]
Thanks for testing. You are right, it works on my machine as well! I suspect that I somehow still had the two Python versions mixed up during execution of the code, which is possibly the reason for why I got the wavelet import error message. So that’s good news, as we won’t require any special treatment in the Python&nbsp;3 case.

**Comment by bwinkel** [comment]
I started working on making the cparametrizer subpackage Py2+3 compatible. Could someone checkout my [fork](https://github.com/bwinkel/SoFiA) and test if everything works as usual? If yes, I'll do a pull request later. (Some of the unit tests fail, but they might just be outdated...)

**Comment by SoFiA-Admin** [comment]
Excellent, thanks a lot for your help! I downloaded and tested your modifications, and they initially still crashed SoFiA due to a Python&nbsp;3 incompatibility issue: in lines 145 and 149 of `parametrisation.py` there is a construct of the form

    d.keys()[i]

In Python&nbsp;3, `dict_keys()` returns a dictionary view object and no longer a list, so it cannot be indexed any more. After explicit conversion of the result of `d.keys()` to a list via

    list(d.keys())[i]

the code runs fine and without any error message on my machine (apart from the WCS crash at the end, of course).

**Comment by bwinkel** [comment]
Nice. Do you prefer a PR or shall I push directly to master?

**Comment by SoFiA-Admin** [comment]
Feel free to push your changes straight away. Thanks again for your help with this matter!

**Comment by paoloserra** [comment]
SoFiA is currently being used under Python 3 so it is in general compatible with it. Any compatibility problems arising in the future should be treated as bugs and have their own issue. Closing this.
