### ISSUE TITLE
Memory leaks in BFfit.h

### ISSUE THREAD

**Issue by sam6321** [SoFiA-Admin/SoFiA#128]
I was running cppcheck over SoFiA and came across a memory leak in BFfit.h:
```
[src/parametrizer/BFfit.h:232]: (error) Memory leak: temp_covar
[src/parametrizer/BFfit.h:232]: (error) Memory leak: w
[src/parametrizer/BFfit.h:232]: (error) Memory leak: v
[src/parametrizer/BFfit.h:232]: (error) Memory leak: soln
[src/parametrizer/BFfit.h:232]: (error) Memory leak: b
```
These leak if the function exits via the following code path (line 232):
```cpp
if(state_flag > 0) {
    covsrt(covar,ma,ia,mfit);
    covsrt(alpha,ma,ia,mfit);
    return 1;
}
```
One solution is to simply delete these variables before returning, or use `std::unique_ptr` to automatically deallocate memory on all return paths.

**Comment by SoFiA-Admin** [comment]
Thank you for reporting these errors. I ran cppcheck myself and get similar error messages:

    [BFfit.h:232]: (error) Memory leak: w
    [BFfit.h:232]: (error) Memory leak: soln
    [BFfit.h:232]: (error) Memory leak: b
    [BFfit.h:1352]: (error) Uninitialized variable: seed

The last message may be incorrect, as `seed` does appear to get initialised in line 1480 before being used. I will leave the memory leak errors for @RussellJurek to check, as he is the author of `BFfit.h` and therefore most familiar with the code.

**Comment by RussellJurek** [comment]
Hi guys. I've confirmed there's no memory leak. cppcheck is being thrown by the fact that I re-initialised the pointers to NULL after deleting the memory they point to.

**Comment by RussellJurek** [comment]
Sorry. Misread the original post. Yes. There is a memory leak when state_flag = 1. I'll fix it up. It's not a serious issue. This situation almost never occurs. It's an edge case protection.

**Comment by SoFiA-Admin** [comment]
Thanks a lot to @RussellJurek for addressing this issue. I just downloaded the fix and ran `cppcheck` again, and it is now happy with the code (apart from the uninitialised `seed` that it erroneously complains about). This issue can therefore be closed now.
