### ISSUE TITLE
Keep pos. and neg. detections separate until after reliability calculation

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#130]
Currently, SoFiA merges positive and negative signals into the same detection when they are within the merging length. A user suggested to instead merge positive and negative sources separately and only combine them **after** reliability calculation. This suggestion was motivated by a case where a significant positive peak was neutralised by a neighbouring negative peak, resulting in the source not being detected due to diminishing integrated flux.

We should discuss this suggestions and determine the statistical implications of the proposed change. It should be noted that the current implementation works spectacularly well on data cubes with Gaussian noise (unless there are significant artefacts), so any change would need to be backed by strong and convincing arguments in its favour.

**Comment by paoloserra** [comment]
I have two comments, the first on the principle, the other on the implementation of the proposed change.

1) In the example given above, how can the user be sure that the positive peak is more significant than the negative peak? Without any prior (e.g., optical counterpart) this assessment will always be questionable. The fact that the negative peak gives as much flux as the positive peak should make one doubt about the significance of the positive peak.

2) How would one implement this? The goal of the reliability calculation is to remove noise peaks from the detection masks. By definition, there are no negative sources in the detection mask after the reliability calculation -- and therefore no negative pixels if one has only merged positive with positive and negative with negative as suggested. So it seems to me that no further merging would be possible after reliability calculation. A further issue is that if we only merge positive with positive the total flux of the detected sources will be always systematically overestimated, particularly for low S/N sources.

In my opinion a much better approach would be to feed SoFiA a flag cube which flags out know artefacts (we could even think of providing a tool to do this within SoFiA). In the absence of significant artefacts it might be better to trust the statistical approach of the reliability calculation, or else impose positivity when merging and find a different way of removing noise peaks (e.g., with the 3D size threshold).

**Comment by paoloserra** [comment]
For completeness, the issue of only merging positive with positive had already been discussed in https://github.com/SoFiA-Admin/SoFiA/issues/34 and had resulted in the commit https://github.com/SoFiA-Admin/SoFiA/commit/820c993d1922ba9a7a884943847921e98d5ed5ae .

(While the idea of post-reliability merging is indeed new.)

**Comment by SoFiA-Admin** [comment]
Thanks for your assessment. I agree with you that the current implementation is statistically meaningful, whereas the proposed change would not. The issue might be one of expectation: users expect strong positive peaks to be associated with astronomical sources, but they don’t create that association with negative peaks of a similar scale. However, from a statistical point of view they should be treated as equal. All of this discussion is of course based on the assumption of statistical noise + astronomical sources being the only signal in the data. Our statistical methods break down as soon as we have to deal with data that contain systematic negative (or positive) artefacts. As you pointed out, merging of only positive pixels was introduced to handle such data, but of course the reliability calculation will no longer work in that case, as its statistical basis is removed.

**Comment by vdhulst** [comment]
To close off this topic: post-reliability merging is an option, but conceptually one should first find sources and do the merging as that is part of the proper source finding. Then the reliability must be applied as it is a statistical way to discriminate between noise (of course only if the data is of good quality) and real detections, based on their place in the parameter space used for the reliability test. So the current approach is conceptually the right one. If data have excessive negative noise then other tools are required to find and remove or flag these noise peaks.
