### ISSUE TITLE
Noise estimator crashes

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#135]
When running the S+C finder on a data cube without negative signals, the S+C finder currently crashes during RMS measurement with the following error message:

    Running S+C filter
        Estimating rms on subcube (x,y,z zoom = 1,1,1) ...    Estimating rms on subcube sampling every 1 voxels ...    ... Subcube shape is (100, 200, 200) ...Traceback (most recent call last):
      File "sofia_pipeline.py", line 313, in <module>
        mask |= pyfind.SCfinder_mem(np_Cube, dict_Header, t0, **Parameters['SCfind'])
      File "build/lib.linux-x86_64-2.7/sofia/pyfind.py", line 56, in SCfinder_mem
        rms = GetRMS(cube, rmsMode=rmsMode, zoomx=1, zoomy=1, zoomz=1, verbose=verbose, sample=sampleRms)
      File "build/lib.linux-x86_64-2.7/sofia/functions.py", line 69, in GetRMS
        rmshisto = np.histogram(cube[z0:z1:sample, y0:y1:sample, x0:x1:sample][~np.isnan(cube[z0:z1:sample, y0:y1:sample, x0:x1:sample])], bins=bins)[0]
      File "numpy/lib/function_base.py", line 199, in histogram
        sa.searchsorted(bins[-1], 'right')]
    IndexError: index out of bounds
    Pipeline failed with exit code 1.

There should either be a graceful exit, or a different RMS measurement algorithm should be picked if no negative signal is present.

**Comment by paoloserra** [comment]
@SoFiA-Admin please test.

**Comment by SoFiA-Admin** [comment]
Thanks, should work, although I slightly modified the code again to outsource sanity checking into a new error module that I created. I also implemented additional checks for the other noise measurement algorithms in the same function which had a similar problem. This issue is now resolved and can be closed.
