### ISSUE TITLE
Compression of output files crashes

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#139]
When processing a 6.3 GB subcube of a 12.6 GB data cube, SoFiA crashes when trying to write the compressed mask cube. The error message indicates that some value does not constitute an integer number (I will try to reproduce the error again to capture the exact error message). A functioning work-around is to disable compression of output products and manually compress output files after the pipeline run is finished.

**Comment by SoFiA-Admin** [comment]
I managed to reproduce the error, and the problem is that some array size is larger than what can be stored in an integer variable:

```
File "/usr/lib64/python2.7/gzip.py", line 235, in write
  self.crc = zlib.crc32(data, self.crc) & 0xffffffffL
OverflowError: size does not fit in an int
```

The issue seems to be with zlib which is used by Python for compression of data.

**Comment by paoloserra** [comment]
As discussed, let's try to catch this with try/except. This won't solve the problem but simply deliver an uncompressed file and prevent the code from crashing.
