### ISSUE TITLE
Enhance size filtering of Linker

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#141]
Currently the Linker can be used to reject sources based on:
- minimum size along X axis
- minimum size along Y axis
- minimum size along X axis

To this we want to add (and include in the GUI):
- maximum size along X axis
- maximum size along Y axis
- maximum size along Z axis
- maximum nr of lines of sight
- maximum total nr of voxels
- minimum nr of lines of sight
- minimum total nr of voxels

**Comment by RussellJurek** [comment]
Hi everyone,
           these are the proposed new SoFiA parameters for the linker module.

merge.maxSizeX [hidden]
merge.maxSizeY [hidden]
merge.maxSizeZ [hidden]
merge.minVoxels 
merge.maxVoxels [hidden]
merge.minLoS 
merge.maxLoS [hidden]
merge.minFllFctr [hidden]
merge.maxFllFctr [hidden]

This only requires two new options to be added to the GUI. The rest are advanced options that can only be specified manually. My philosophy is that most users only need to worry about setting a minimum value for these parameters. Allowing them to set a maximum value without understanding what they're doing could result in poor results.

I've added the 'fill factor' to the list of thresholding parameters. The linker is already capable of using this information (the fraction of bounding box voxels that are marked as source) to reject weird, splotchy, noise dominated masks. It's just always been coded to use a default value that turns it off.

Cheers,
Russell

**Comment by SoFiA-Admin** [comment]
Thank you, @RussellJurek, for implementing those features. I have run a few basic tests and found the maximum x, y and z size thresholds to work as expected.

> My philosophy is that most users only need to worry about setting a minimum value for these parameters.

We’ve actually had a user already who was in need of the maximum size threshold, as she had large-scale artefacts in her data that she needed to get rid of, so the maximum size thresholds might be useful to have in the GUI, and I have added those to the merging tab, where merging radius, minimum size and maximum size can now be controlled separately for the three axes.

My questions to all of you is whether you think we should add the merge.minVoxels and merge.minLoS to the GUI as well, as @RussellJurek suggested?

**Comment by paoloserra** [comment]
It seems there is no interest to have those additional source size filters implemented in the GUI. As far as I'm concerned it's OK to keep those outside the GUI for expert users. Closing this issue for now, please reopen if necessary. For completeness, the new parameters requested by this issue have been added in https://github.com/SoFiA-Admin/SoFiA/commit/2c80693199525590f9280c5191e0c69e9490a8c5 .
