### ISSUE TITLE
Reduce impact of continuum-subtraction residuals

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#142]
It would be useful to minimise the impact of continuum-subtraction residuals on the results of SoFiA. These residuals can produce bright (both positive and negative) sources and affect the results of the reliability calculation.

These sources are typically very extended along the Z axis. https://github.com/SoFiA-Admin/SoFiA/issues/141 will provide a tool to reject these sources prior to parameterisation through a maximum Z-size threshold.

We could investigate two additional solutions.

1. Flag troublesome lines of sight prior to source finding. This could be done by measuring the rms of all lines of sight and flagging those with an anomalously high rms. I see this as an extension of the "global noise scaling" algorithm. I suggest we add a 4th choice (XY) to the "dimensions" of that algorithm. Such a new option would allow us to normalise the noise of the cube per line of sight. Additionally, we could then include an option to flag lines of sight with anomalously high rms. In fact, this could be a general option available for all choices of "dimension": X, Y, Z and XY.

2. After source finding and before merging, remove from the mask all lines of sight whose fraction of detected voxels is too high. The actual threshold would be a free parameter ranging from 0 to 1. Again, this could be a more general functionality that we could offer not just for anomalous lines of sight (XY "mode") but also for anomalous channels (Z "mode").

**Comment by paoloserra** [comment]
An example of the masking of LOS's with anomalously high noise. In this case I did the following:
- measure the negative-voxels, two-pass MAD noise of the entire cube (rms_0) following noise normalisation along the Z axis (this was just a sanity check, as it should be rms_0 = 1);
- measure the two-pass MAD noise of each LOS rms(x,y);
- flagged all LOS's where rms(x,y,) > rms_0 + 2.5 STD[rms(x,y,)];
- extended the flag to a all neighbouring LOS's in a square box of side = 3 pix.

![slice_nomask](https://user-images.githubusercontent.com/6591265/46936732-9e3bf480-d05f-11e8-90b1-4a404ff61b83.png)
![slice_mask](https://user-images.githubusercontent.com/6591265/46936733-9e3bf480-d05f-11e8-99a8-2c6e91d7d085.png)

**Comment by paoloserra** [comment]
The image below shows a channel of the cube after masking bad LOS's. The contours are from the continuum image. In this case all flagged LOS's are at the edge of the field. This makes sense as the continuum was subtracted with UVLIN, which does not work well far from the phase centre.

![xyview](https://user-images.githubusercontent.com/6591265/46939524-c5e28b00-d066-11e8-894d-0be324bf9e53.png)

Below are two spectra. The first is a spectrum that was masked. It is one of the faint continuum sources to the SE. The second is a spectrum that was not masked. It is the brightest continuum source in the field, some 20 arcmin N of the phase centre.

![badspectrum](https://user-images.githubusercontent.com/6591265/46939522-c5e28b00-d066-11e8-9e18-2abdff59d4d0.png)
![goodspectrum](https://user-images.githubusercontent.com/6591265/46939523-c5e28b00-d066-11e8-9219-325e79f9f98a.png)

**Comment by vdhulst** [comment]
Interesting. So clearly associated with effects at the edge of the primary beam. Is the beam symmetric? if not it could produce a systematic effect as shown in the top spectrum. Would be interesting to also plot a spectrum on the source to the east of the FC.

**Comment by vdhulst** [comment]
thanks Paolo, I meant (my mistake) the source to the west (ra=08:30:40, dec=-35:51:00), the one that was flagged. It is a bit father from the field centre than the one you plotted, which I agree does not need flagging.

**Comment by paoloserra** [comment]
No worries. Here it is.

![westspectrum](https://user-images.githubusercontent.com/6591265/46943833-da2b8580-d070-11e8-9b3f-5ad2e82112df.png)

**Comment by paoloserra** [comment]
Two of the methods suggested at the top of this issue have now been implemented and are being used with success: 1) reject sources based on maximum size (X,Y,Z,Nvox,Nlos); 2) flag "bad" LOS's prior to source finding. The third method suggested above was:

> After source finding and before merging, remove from the mask all lines of sight whose fraction of detected voxels is too high. The actual threshold would be a free parameter ranging from 0 to 1. Again, this could be a more general functionality that we could offer not just for anomalous lines of sight (XY "mode") but also for anomalous channels (Z "mode").

This third method has not been implemented yet, but it may be redundant given the success of the other two methods. I will therefore close this issue for now. If interest in this last method grows again we can open a new issue.
