### ISSUE TITLE
Python modules version check in setup file

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#144]
We have minimum version reqirements for numpy, scipy and astropy in setup.py. These are checked with the StrictVersion function from python distutils.version (see https://github.com/python/cpython/blob/master/Lib/distutils/version.py#L93). As the name suggests, this function is very strict about version names and does not allow suffixes like e.g. 'dev' appended to the version number. Since I have encountered this problem with manually installed development versions of python libraries a number of times already, I suggest to switch to the LooseVersion comparison (see https://github.com/python/cpython/blob/master/Lib/distutils/version.py#L267), which is a bit more forgiving. Any thoughts or objections?

**Comment by SoFiA-Admin** [comment]
Thank you to @ngiese for identifying and fixing this problem (see 83ac6e4d2a884373ff006dc7d765b4bc12ce2cc1). The issue can now be closed.
