### ISSUE TITLE
Some parameter values not updated after mask dilation

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#145]
I run the current SoFiA master on the wiki's test cube and found that the value of the parameters *_geo, *_min, *_max, n_pix, n_chan and n_los in the output catalogue is not updated after mask dilation. That is, their value in the output catalogue is still the one returned by the linker.

I think it would be better to recalculate the value of these parameters in the parameterisation module and update the output catalogue accordingly.

**Comment by ngiese** [comment]
With commits 4ef5789 and 0ed685b all mentioned parameters should be updated. Please test.

**Comment by SoFiA-Admin** [comment]
Thank you, @ngiese, for fixing this issue so quickly. I am wondering if mask optimisation could be affected by the same problem? I checked the code in `MaskOptimization.cpp` and can confirm that the source bounding boxes are getting updated, but none of the other parameters that @paoloserra mentioned. Unless this happens at a later stage, we will presumably be facing the same issue again.

**Comment by ngiese** [comment]
I added the update of the other parameters (81d2626).

**Comment by SoFiA-Admin** [comment]
Thanks a lot for the quick fix!

**Comment by paoloserra** [comment]
Thanks for resolving this issue @ngiese !
