### ISSUE TITLE
Failed noise calculation and wrong f_int in parameterisation module

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#146]
I run the current SoFiA master on the wiki's test cube with the attached parameter file and find that the noise calculation fails for 2 out of 4 detected sources. SoFiA gives a warning about this.

I've noticed that for those same sources (and only for those) the value of f_int in the output catalogue is different from the simple sum of all voxel values of those objects. Regardless of whether the mask of those objects is good (in fact, it is not), I do not understand the reason for this discrepancy.

I have verified that the mask of those objects does not include any infinite or NaN voxel values.

[haynes.par.zip](https://github.com/SoFiA-Admin/SoFiA/files/2286405/haynes.par.zip)

**Comment by ngiese** [comment]
As far as I can judge from the code for the dilation in parameterisation.py (https://github.com/SoFiA-Admin/SoFiA/blob/master/sofia/parametrisation.py#L23), we do not update the objects array. This means, that the bounding boxes around our sources are too tight for the noise to be correctly estimated, especially for sources, that are quite compact in the 3D cube. You can see that in the following portion of the noise estimation: https://github.com/SoFiA-Admin/SoFiA/blob/master/src/parametrizer/Parametrization.cpp#L215
For every pixel in the bounding box, we check if the corresponing pixel in the mask has been assigned to a source ID. If not (if the mask pixel has the value 0), it is considered for the MAD noise estimation, which happens a few lines further down. In your case, the bounding boxes of the two sources, for which the noise cannot be estimated lies completely within the dilated cube. There are, thus, no pixels left, for which the noise could be estimated. I guess, the solution is to update the bounding boxes in the dilation part. In fact, that should also solve issue #145. I'll change that bit and let you know if fixes anything.

**Comment by ngiese** [comment]
Should be fixed with commit 4ef5789. Please test.

**Comment by paoloserra** [comment]
Thanks @ngiese , tested and it's all good -- both the noise calculation and the value of f_int.

Do you understand why in case of failed noise calculation the value of f_int was wrong? Note that f_int was correct for objects where the noise calculation was successful.

**Comment by paoloserra** [comment]
> Do you understand why in case of failed noise calculation the value of f_int was wrong? Note that f_int was correct for objects where the noise calculation was successful.

OK, it was because of the same reason. The dilated source extended outside the old bounding box, and since the flux was calculated only considering voxels inside the bounding box some flux was missing. All in order now.
