### ISSUE TITLE
Create cube splitting script

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#153]
To facilitate parallelisation, we should start by creating a separate script that can be used to automatically split large data cubes into smaller ones that can be processed separately through SoFiA. The script should automatically figure out the optimal splitting strategy based on the amount of memory available.

**Comment by paoloserra** [comment]
I'm closing this issue since the parallelisation of SoFiA is going to happen within the context of SoFiA-2 instead.
