### ISSUE TITLE
SoFiA crashes when run on 2D image

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#155]
SoFiA currently crashes when run on a 2-D image that does not have a third axis of size 1 defined. This happens during the generation of moment maps, apparently while trying to access the non-existing `CTYPE3` keyword from the header. The full error message is attached below.

    Writing moment-0
    Traceback (most recent call last):
      File "/SoFiA/git/sofia_pipeline.py", line 691, in <module>
        writemoment2.writeMoments(np_Cube, mask, outroot, debug, dict_Header, Parameters["writeCat"]["compress"], write_mom[0], write_mom[1], Parameters["writeCat"]["overwrite"])
      File "writemoment2.pyx", line 111, in writemoment2.writeMoments (src/writemoment2/writemoment2.c:3633)
      File "/python2.7/dist-packages/astropy/io/fits/header.py", line 152, in __getitem__
        card = self._cards[self._cardindex(key)]
      File "/python2.7/dist-packages/astropy/io/fits/header.py", line 1729, in _cardindex
        raise KeyError("Keyword %r not found." % keyword)
    KeyError: "Keyword 'CTYPE3' not found."
    Pipeline failed with exit code 1.

**Comment by paoloserra** [comment]
I've tested the fix implemented by @ngiese and this works fine now. SoFiA can be run on a 2D image and will still produce a moment-0 image = masked input image . I've tested most other modules, including noise scaling (also along Z), SCfind (including filters with a non-zero Z component), merging (including a merging radius > 1 chan), reliability, source parameterisation and catalogue creation. It all seems to work fine.
