### ISSUE TITLE
Output format for source parameter values

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#157]
A user reported that all of the flux values in the SoFiA output catalogue are zero. The reason for this appears to be that the flux values in the data cube are very small. Unfortunately, the output precision in the SoFiA source catalogue is currently hard-coded to be `%12.4f` in line 238 of the file `sofia/parametrisation.py`. However, this default turned out to be insufficient in this specific case.

It would be highly desirable to allow more flexibility here, e.g. by either allowing the user to choose a precision, or by automatically choosing an appropriate precision based on the actual value to be written. In the interim, I will increase the default precision to a value greater than 4 to ensure that in the majority of cases the default provides sufficient dynamic range.

**Comment by paoloserra** [comment]
Why not replacing "%16.8f" with something like "%16.6e" in the following line?

https://github.com/SoFiA-Admin/SoFiA/blob/38d20ab0c9c1dae35ddda7e8ea2272ccd318a589/sofia/parametrisation.py#L238

**Comment by SoFiA-Admin** [comment]
In principle, that’s fine with me. By the way, SoFiA 2 chooses the format automatically, using floating-point notation for values in the range of 1e-3 ≤ x < 1e+4 and scientific notation otherwise. The only downside is that you may end up having mixed formatting in columns with values extending across the boundary.
