### ISSUE TITLE
Catalogue-based source finding failing

### ISSUE THREAD

**Issue by jdelhaize2** [SoFiA-Admin/SoFiA#160]
Catalogue-based source finding fails when run on my mac laptop. Python-3 problem? Output in GUI copied below.

Cheers,
Jacinta Delhaize
jacinta@ast.uct.ac.za

--- SoFiA: Reading default parameters ---
Traceback (most recent call last):
  File "/Users/jacinta/Downloads/SoFiA-master/optical_find.py", line 285, in <module>
    cat = list(reader)
  File "/anaconda3/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/anaconda3/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

--- SoFiA: Reading user parameters ---
Parameters extracted from: SoFiA.session

Working on cube: /Users/jacinta/Dropbox/jacinta/workdir/mightee-hi/paolo_test/sofiatest/sofiatestcube.fits
Working on catalogue: /Users/jacinta/Dropbox/jacinta/workdir/mightee-hi/paolo_test/opticalcatalogue.csv
Pipeline failed with exit code 1.

**Comment by jdelhaize2** [comment]
* When run on the sofia test cube with a catalogue containing two sources.

**Comment by paoloserra** [comment]
@jdelhaize2 can you please test this and reopen the issue if necessary? Thanks!
