### ISSUE TITLE
Installation error on Mac

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#162]
A user tried to install SoFiA on a Mac OS 10.7, and reported the following installation error:

    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda3/include -arch x86_64 -I//anaconda3/include -arch x86_64 -Isrc -Isrc/linker -I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I//anaconda3/include/python3.7m -c src/linker/linker.cpp -o build/temp.macosx-10.7-x86_64-3.7/src/linker/linker.o -O3
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on
          the command line to use the libc++ standard library instead
          [-Wstdlibcxx-not-found]

The error message indicates that the C++ standard library was not found. This is likely due to Apple’s decision to no longer support the GNU C++ standard library in Clang (e.g.: [https://forums.developer.apple.com/thread/106114](https://forums.developer.apple.com/thread/106114)).

A workaround might be to pass the additional argument `-stdlib=libc++` on to Clang in this case by changing all of the `extra_compile_args` in the `setup.py` script. This will tell Clang to use Apple’s own C++ library instead. For example,

    extra_compile_args = ["-O3"]

could be changed to

    extra_compile_args = ["-O3", "-stdlib=libc++"]

and so forth. This would only work for Clang on Mac, though, as GCC does not support the `-stdlib` argument.

In the longer term, however, we will need to address this problem if we want to continue to support Clang, as other users with newer versions of Mac OS will likely be facing the same problem.

**Comment by SoFiA-Admin** [comment]
Following up on the initial report, the user tried to compile SoFiA with the `-stdlib=libc++` option. While this solved the original problem, it caused all kinds of secondary error messages. Here is a short excerpt from the rather lengthy list of messages:

    src/linker/linker.cpp:1565:7: warning: expression result unused [-Wunused-value]
          __pyx_v_objects;
          ^~~~~~~~~~~~~~~
    src/linker/linker.cpp:4073:134: warning: code will never be executed
          [-Wunreachable-code]
      ...__pyx_t_2++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[1]; __pyx_li...
                                                             ^~~~~~~
    src/linker/linker.cpp:6068:21: error: no member named 'exc_type' in '_ts'
        *type = tstate->exc_type;
                ~~~~~~  ^
    src/linker/linker.cpp:6069:22: error: no member named 'exc_value' in '_ts'; did
          you mean 'curexc_value'?
        *value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
    //anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared
          here
        PyObject *curexc_value;
                  ^
    src/linker/linker.cpp:6070:19: error: no member named 'exc_traceback' in '_ts';
          did you mean 'curexc_traceback'?
        *tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
    //anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback'
          declared here
        PyObject *curexc_traceback;

If anyone has any idea of what is going on, please let me know. Unfortunately, I don’t have access to a Mac, so won’t be able to reproduce the problem myself.

Another note: the user appears to be using Python 3.7; could this have contributed to the problem in some way?

**Comment by RussellJurek** [comment]
I think the problem is that we use Cython to create a wrapper around C++
libraries. It does this by using boiler plate code in many places. Some of
this code goes unused or is unreachable. That bloat is the cost of writing
a generically usable code block. If they're only getting warnings and not
errors, then the code should still have complied. Unless they used either
the 'elevate warnings to errors' or 'error on too many warnings' compiler
flags.

**Comment by bwinkel** [comment]
Problems with compiled code are quite common on MacOS, unfortunately. It is often the case, that libraries are located in non-standard directories, and the default Clang installation still provides no OpenMP support.

If you want to do your users a favor, the best option would be to provide packages for the Anaconda distribution via [conda-forge](https://conda-forge.org/). Additionally, one could produce wheels and upload them to [PyPI](https://pypi.org/), such that people can install the binaries with a simple `pip install`. Both will require some effort, but CI/CD systems such as Travis or Azure can do all of this (including unit testing) automatically.

**Comment by SoFiA-Admin** [comment]
Thanks everyone for your feedback on this issue. After a discussion at today’s meeting we concluded that the issue is most likely caused by the fact that Mac OS 10.7 was published in 2011 and is more than 8 years old now. The version of Clang use for compiling SoFiA is likely to be equally ancient and for that reason unlikely to work. Back then we did not official support Clang, as it was know to be unable to compile the SoFiA source code. This issue can therefore be closed as “won’t fix”. We can reopen if new information becomes available.

**Comment by RussellJurek** [comment]
Aha! I wonder if the issue is that this code was cythonised using OS X 10.7. It wouldn’t surprise me if the boiler plate code changes slightly with each version of OS X. Then it would no longer be configured to compile properly. It would explain Thijs results. 

Three options:
1. Re-run cython periodically. 
2. Maintain a library of cython versions. 
3. Make cython a requirement and include cython in the installation script. 
4. Add instructions for doing #3 yourself to the FAQ and the install/readme files. 

Cheers,
Russell

**Comment by bwinkel** [comment]
AFAIK, the cythonized c-file is only dependent on the Cython version, not the OS (it's creation doesn't involve a C compiler). Furthermore, in my experience, if you create a file with a new Cython version, it is usually backwards compatible to high degree. Therefore, re-running Cython periodically should fully suffice. Again, this is something that could be completely automatized in a CI/CD framework...

**Comment by paoloserra** [comment]
Reopening this issue until we hear a confirmation that the fix implemented by @vdhulst  in https://github.com/SoFiA-Admin/SoFiA/tree/MacOS solves this problem.

**Comment by paoloserra** [comment]
OK, we got confirmation that this solved the problem, thanks @vdhulst ! Will merge https://github.com/SoFiA-Admin/SoFiA/tree/MacOS into master.

**Comment by paoloserra** [comment]
https://github.com/SoFiA-Admin/SoFiA/pull/165
