### ISSUE TITLE
Compilation of GUI fails

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#173]
Compilation of the GUI failed on a freshly installed Kubuntu 20.04 using Qt 5.12.8 with the error message

```
WidgetDataViewer.o: relocation R_X86_64_32S against symbol `_ZTV16WidgetDataViewer' can not be used when making a PIE object; recompile with -fPIE`
/usr/bin/ld: main.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
```

I am not entirely sure what is causing the problem, but adding the `-fPIE` option to the `QMAKE_CXXFLAGS` in the file `gui/SoFiA.pro` resolved the issue, and the GUI is now compiling and working fine. I am not sure if we should generally make that change, as we may first want to figure out what the consequences are.

**Comment by RussellJurek** [comment]
PIE is analogous to the -fPIC command to compile 'Position Independent Code' for shared/dynamic libraries. -fPIE takes it another step. It's 'Position Independent Executables'. It can only be linked to executables. You can't use it to make a library in most cases, but it allows you to write units (source code files) for C++ without having to follow strict declaration syntax.

**Comment by SoFiA-Admin** [comment]
For some reason I cannot reproduce this problem anymore after deleting my local repository and recreating it from scratch using the copy from GitHub. Everything compiles and works fine now, so my suspicion is that the problem was caused by the presence of old configuration and object files from the old installation that somehow interfered with the new setup after updating my operating system.

I will therefore close this issue now, as it does not appear to be relevant any longer.
