### ISSUE TITLE
Wavelet module broken

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#174]
The latest version of SoFiA installed on the latest version of Kubuntu 20.04 fails to run with the following error message right at the start:

    Traceback (most recent call last):
      File "/SoFiA/git/sofia_pipeline.py", line 23, in <module>
        from sofia import wavelet_finder
      File "/SoFiA/git/sofia/wavelet_finder.py", line 4, in <module>
        from sofia import wavelet as wv
    ImportError: cannot import name 'wavelet' from 'sofia' (/SoFiA/git/sofia/__init__.py)

The problem appears to be that the module named `wavelet` doesn’t exist. My first suspicion was that there is an issue with cython, so I tried to re-cythonize the `wavelet.pyx`. This resulted in a warning message that `language_level` wasn’t set and assumed to be 2 by default. This would make no sense, as I am using Python 3, so I added the line

    #cython: language_level=3

at the start of the `wavelet.pyx` file to force the language level to 3. When I do this, however, cython fails to compile the code altogether and produces a string of error messages of the type `Cannot assign type 'double' to 'int'`, suggesting that `wavelet.pyx` is in principle not compatible with Python 3.

**Comment by bwinkel** [comment]
I'll look into this.

**Comment by SoFiA-Admin** [comment]
Thanks a lot, @bwinkel.

**Comment by bwinkel** [comment]
Well, I'm not even making it that far. I tried to install sofia in a conda environment:

```bash
# after cloning sofia from github
cd sofia

conda create -c conda-forge --yes -n sofia3.7 python=3.7 astropy cython ipython matplotlib numpy "pyqt>=5.6" scipy zlib
conda activate sofia3.7

rm -rf build
python setup.py build --no-gui=True --force
> g++: error: build/lib.linux-x86_64-3.7/sofia/cparametrizer.cpython-37m-x86_64-linux-gnu.so: No such file or directory
```

I cythonized the cparametrizer.pyx with the newest cython version, but get the same error. Any idea, what's going on? 

By-the-way, I think your setup.py could use some love. Nowadays, it is very easy to achieve that the package is correctly installed into the "site-packages" of the Python distribution (be it the user directory for the OS python installation or an Anaconda environment etc.). Fiddling with the PYTHONPATH is discouraged. In fact, I would even recommend that you create binary packages for the major platforms (wheels or conda packages) as this will make installation for your users much much easier, especially when you rely on compiled extensions. I'm willing to help, but it certainly requires some efforts...

**Comment by SoFiA-Admin** [comment]
Interesting, that’s not an error message I’ve ever seen before. From the look of it, the installation script did not build the `cparametrizer.so` for whatever reason. Are there any other error messages further up that could point to why the shared object code wasn’t built? Cython issues/incompatibilities would have been my first guess as well...

Thanks also for your comments on the setup file. This is something we should discuss at our next telecon given that the current setup file is pretty much still the same as 8 years ago when we started the project, so there should be plenty of room for improvement of the installation procedure.

We have had lengthy discussions about binaries or Docker images in the past, but never ever proceeded with these plans. This might be worth considering again given that it seems to be getting increasingly difficult to get SoFiA installed successfully.

**Comment by bwinkel** [comment]
> Are there any other error messages further up that could point to why the shared object code wasn’t built?
No, that is the strange part. It seems to compile fine. (There are only a few warnings, which should not be problematic in my experience.) Also, all other C extensions are built and present in the build-directory.

I deal with cython extensions a lot, but something like this I never encountered before. At the moment, I have no clue what's going on. Perhaps it is related to my use of (a rather new) Anaconda? Has anyone tried to install in a conda environment before? Since a few releases, Anaconda comes with it's own compilers... (which could by the way also be the solution to your OpenMP issues on MacOS.)

**Comment by bwinkel** [comment]
OK, I tried the same with an Anaconda on my workstation at the institute (Ubuntu 18.04). There it works. I didn't have to re-cythonize any files. (The cython language level is only important for the the pyx file itself as the extension should run on both, Python 2 and 3, if I'm not mistaken.) 

In another test, I will try to see what happens, if I indeed re-cythonize the various Cython extensions. For the cparametrizer extension, I already noted that there is a warning:

```bash
.../miniconda/envs/sofia3.7/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release!
```

Usually, it should suffice to add the following to the `pyx`-files:
```python
#!python
# -*- coding: utf-8 -*-
# cython: language_level=3
```
But the third line was already present in this case. According to [this post on StackOverflow](https://stackoverflow.com/questions/34603628/how-to-specify-python-3-source-in-cythons-setup-py) another solution is to modify the `cythonize.py` script:

```python
cythonize(pyx_src, compiler_directives={'language_level' : "3"})
```
which indeed did the trick.

For the wavelet module, there is no `cythonize.py`, so I just ran `cython -a wavelet.pyx` and again the same warning appears. This time, however, adding the language level to the pyx file helped. I now ran into some warnings and error related to the cython compiler, e.g., 

```bash
warning: wavelet.pyx:413:20: Too many arguments for format placeholders

Error compiling Cython file:
------------------------------------------------------------
...
        int kernelsize = kernel.shape[0]
        int index, i, j
        double a

    for i in range(size):
        index = i - kernelsize/2 * stepsize
                 ^
------------------------------------------------------------

wavelet.pyx:40:18: Cannot assign type 'double' to 'int'
```
These should be easy to fix. I'll look into this next and keep you posted.

**Comment by bwinkel** [comment]
I was able to re-cythonize all modules and installation and running the test cube seems to work. (That doesn't necessarily mean that it will work on the problematic machines, but it may be worth a try.) As I did some minor changes - do you want me to open a proper pull request from a fork on my own GitHub space, or can I just push the changes to a new branch on the Sofia repository directly?

**Comment by SoFiA-Admin** [comment]
@bwinkel Thanks a lot for your help with getting the modules recythonized. I’d certainly be keen to test this on my machine to see if I can get it to work.

> do you want me to open a proper pull request from a fork on my own GitHub space, or can I just push the changes to a new branch on the Sofia repository directly?

Either way is fine with me. Feel free to push the changes directly if you like.

**Comment by SoFiA-Admin** [comment]
Thank you, @bwinkel, for updating the Cython code to make it compatible with Python 3. This appears to have resolved the issue, and the only thing left to do for me is to update the Python version requirement in the README file, as we will probably want to officially drop support for Python 2.7 at this stage.

I will close this issue now, but please feel free to re-open if you continue to encounter problems related to Cython version incompatibilities.
