### ISSUE TITLE
Binary mask from SoFiA 2 to be used into SoFiA 1

### ISSUE THREAD

**Issue by aychasam** [SoFiA-Admin/SoFiA#175]
Dear SoFiA-Admin,

I get the following error when I try to set a mask in SoFiA 1.3.1.
This mask was the output from the binary mask `output.writeRawMask        =  true` from SoFiA 2.2.0.
```
ERROR: Input cube and mask are not on the same WCS grid.
141.347958333 141.347958333 -52.6112777778 -52.6112777778 23728921.1982 23728921.1982
```
However, they came from exactly the same dataset. 
I do not encounter the error when I use the output mask from `steps.doWriteMask	=	true` from SoFiA 1.3.1.

**Comment by SoFiA-Admin** [comment]
As this problem is mostly about SoFiA 1, I have transferred the issue from the SoFiA 2 to the SoFiA 1 repository.

**Comment by aychasam** [comment]
Sure, thank you.

**Comment by SoFiA-Admin** [comment]
@aychasam I have uploaded a fix that simply turns the error message into a warning without exiting from the pipeline (ca205d00f4e71f0d2aada96e42767d56a59384cc). Please feel free to download and install the latest version of SoFiA (https://github.com/SoFiA-Admin/SoFiA/archive/master.zip) and check if loading the SoFiA 2 mask works fine now.

**Comment by aychasam** [comment]
Sure, I will try it. I am actually running SoFiA 1 on the ilifu cloud so I will ask them to update to the latest version maybe?
Thank you very much for your help.

**Comment by paoloserra** [comment]
You'd need them to install the current master version of SoFiA.

**Comment by aychasam** [comment]
There is no error anymore for now.
Thank you very much for all the help.
