### ISSUE TITLE
contsub.enable is an unknown parameter

### ISSUE THREAD

**Issue by thabsko** [SoFiA-Admin/SoFiA#176]
Hello, 

Following the SoFiA 2 manual, I am attempting to perform continuum-subtraction on spectral image cube with the following input being included in my parameter file: 

contsub.enable = true
contsub.order = 0
contsub.threshold = 3.0
contsub.padding = 2

The process returns an error as follows: 
____________________________________________________________________________

 Pipeline started
____________________________________________________________________________

  Using:    Source Finding Application (SoFiA)
  Version:  2.2.0 (27-May-2020)
  CPU:      6 cores available
  Time:     Fri Sep 11 18:29:51 2020

____________________________________________________________________________

 Loading parameter settings
____________________________________________________________________________

  Activating SoFiA default parameter settings.
  Loading user parameter file: '4C03_sofia_CI.txt'.

    **Unknown parameter: 'contsub.enable'
    Unknown parameter: 'contsub.order'
    Unknown parameter: 'contsub.threshold'
    Unknown parameter: 'contsub.padding'**

ERROR: Unknown parameter settings encountered. Please check
       your input or change 'pipeline.pedantic' to 'false'.
       Terminating with error code 7.

I know it's not a typo. 
Why are the `contsub` variable inputs considered unknown parameters?

**Comment by paoloserra** [comment]
There might be some mix-up between SoFiA and SoFiA-2. The present issue was opened on the SoFiA repository, and maybe that's the software you are running. However, the contsub module does not exist in SoFiA. It exists in SoFiA-2, see https://github.com/SoFiA-Admin/SoFiA-2 . To use that module you'll need to install and run SoFiA-2 instead of SoFiA.

**Comment by thabsko** [comment]
Indeed there has been a mix up in installed versions. With SoFiA 2 running, I have been able to use the above parameters within my source-finding procedure.
Thank you!

**Comment by thabsko** [comment]
Indeed there has been a mix up in installed versions. With SoFiA 2 running, I have been able to use the above parameters within my source-finding procedure.
Thank you!
