### ISSUE TITLE
Saving intermediate results 

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#24]
If the pipeline terminates due to an error in a module, intermediate products such as weight cubes, are lost. It would be nice if in case of errors the pipeline could be terminated properly and intermediate products saved. This could be implemented as another option that the user can choose.

**Comment by SoFiA-Admin** [comment]
It would be useful to generally produce output as soon as possible in the pipeline to ensure that as much data as possible has been written when the pipeline crashes. In part this is already the case (e.g. filtered cube, noise cube), but the mask cube could be written much earlier than currently done right after reliability calculation.

**Comment by SoFiA-Admin** [comment]
As discussed at today’s meeting, most data products are now generated as soon as they have been created, so this issue can be closed now, as it is no longer a high priority at this point in time.
