### ISSUE TITLE
Test of SoFiA installation

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#27]
In order to test, if the SoFiA installation works correctly, we agreed that we would provide the user with an example cube, that the pipeline can be tested on.

I added some lines to the end of the setup.py file that show the user how to test their SoFiA installation. These lines are commented out. If you add a directory with the name "test_data" containing the sample cube and the parameter file to the main SoFiA directory (SoFiA-master), you can just uncomment the last lines in setup.py.

**Comment by paoloserra** [comment]
sofiatestpar.par on Wiki needs to be updated/checked.

**Comment by SoFiA-Admin** [comment]
A test data set has been created and is provided for download on the GitHub wiki. This issue can now be closed.
