### ISSUE TITLE
SoFiA uses an unexpected large amount of memory

### ISSUE THREAD

**Issue by apopping** [SoFiA-Admin/SoFiA#37]
I tried to use SoFiA on a ~540 Mb cube with very basic settings, using only the threshold filter. To my surprise it almost froze my laptop and used close to 5Gb of memory, where I expected to use less than 1Gb.
Also when using a smaller cube, the actual memory usage was significantly more than expected.

**Comment by paoloserra** [comment]
These problems have been solved. Memory usage is documented in Serra et al. (2015). Memory usage is still excessive for the experimental 2d-1d implementation but we will open a separate issue on that.
