### ISSUE TITLE
functions.GetRMS() histogram method not working for non-zero mean data

### ISSUE THREAD

**Issue by bwinkel** [SoFiA-Admin/SoFiA#38]
The histogram method of functions.GetRMS(), i.e., rmsMode='negative', doesn't take into
account that the cube could have non-zero mean. The issue is that the histogram bins
are calculated for the interval [data.min(), -data.min()].

Furthermore the default value for nrbins=10000 seems quite large given that the standard behavior is to use only few planes of the data cube (zoomz=10000).
I assume that it could easily happen, that the histogram is "over-resolved".

```python
from sofia import functions
import numpy as np

noise = np.random.normal(0., 1., (50, 50, 50))

print functions.GetRMS(noise, rmsMode='negative', zoomz=1, verbose=True)
# 0.9979
print functions.GetRMS(noise + 1., rmsMode='negative', zoomz=1, verbose=True)
# 0.5877
print functions.GetRMS(noise + 2., rmsMode='negative', zoomz=1, verbose=True)
# 0.3886
print functions.GetRMS(noise + 4., rmsMode='negative', zoomz=1, verbose=True)
# ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by paoloserra** [comment]
We have decided to check whether the pixel value distribution is centred on zero at the beginning of the code, and issue a warning if that is not the case.

**Comment by SoFiA-Admin** [comment]
This issue can probably be closed now.
