### ISSUE TITLE
Proposal: rename 'sofia' python module name to 'SoFiA'

### ISSUE THREAD

**Issue by bwinkel** [SoFiA-Admin/SoFiA#42]
This needs some explanation. Usually, when you install some python package, you will use either

``` bash
root> python setup.py install
```

or 

``` bash
user> mkdir $HOME/local  # if not already present
user> python setup.py install --prefix=$HOME/local
user> export PYTHONPATH=$HOME/local
```

Personally, I prefer the second option, because you don't need root privileges. From my experience it's working flawlessly.

Now, sofia handles installation quite differently. We have

``` bash
user> python setup.py build
```

which will just compile everything and put it into the source folder "SoFiA/build/some-ugly-lib-dir". Since sofia wasn't installed properly, one then has to put this path manually into the search paths. While this would in principle be ok, I would prefer the more standard approach. Any obligations?

In any case, weird stuff happens, if you start the pipeline from within the source directory.  Because there is a sub-directory 'sofia', python will first look here to import modules when doing 'import sofia' (neglecting the build-directory completely). And on top of this, if one uses the installation approach (which some crazy people like me might do), it won't find the cython-modules, being located in another directory.

Therefore, I propose to rename the python module to 'SoFiA'. Note, that no change to the directory structure is needed, just the sofia setup.py script would need to be slightly modified. And of course, all import statements had to be changed. If you want to try, I'll upload a branch with the necessary modifications.

**Comment by SoFiA-Admin** [comment]
As there would seem to be no real benefit to the proposed changes, the decision has been made to leave the setup as is and close this issues at this stage.
