### ISSUE TITLE
Add flags to output catalog

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#59]
A few reasons to have flags:
1) source close to edge of cube
2) source "contains" NaN's
3) dilation reaches maximum (i.e., flux has not converged)
4) dilation makes objects overlap

**Comment by paoloserra** [comment]
This is mostly done now. The only missing flag is one for objects where mask dilation stops because it's reached the maximum allowed and not because the flux has converged. To do this it would be good to define the flag parameter in parametrisation.dilate and then pass it on to parametrisation.parametrise, which will update it if necessary.

**Comment by SoFiA-Admin** [comment]
This has mostly been implemented by now, so the issue can be closed. If additional flags are required, a new issue can be created.
