### ISSUE TITLE
further packages needed for compilation

### ISSUE THREAD

**Issue by xipmix** [SoFiA-Admin/SoFiA#81]
For a Debian system (Jessie release) at least...
* python-dev (for pyconfig.h)
 * qt4-qmake, libqt4-dev (for qmake, QtGlobal, QtGui/*, QtCore/* etc)
 * qt5-qmake, qtbase5-dev (ditto)

**Comment by RussellJurek** [comment]
The SoFiA GUI is written in C/C++ using Qt. Qt needs to be installed before the SoFiA GUI can be compiled. Have you installed Qt on your machine?

**Comment by xipmix** [comment]
Yup. I opened this because I wanted to document the specific package names I needed as it took a while to track down the particular ones that are needed. Perhaps this is WONTFIX but had the last sentence under 'Requirements' read:

You will also need the corresponding development packages:
       GNU Scientific Library
       Qt (QtGlobal, QtCore, etc)
       qmake

it would have made the task of figuring out what to install easier.

**Comment by RussellJurek** [comment]
Okay. This is very surprising. qmake is part of the Qt package and should have been installed as part of it. The q in qmake is for Qt. That's why it isn't listed explicitly in the requirements.

**Comment by SoFiA-Admin** [comment]
Thanks for reporting this issue. I added the extra requirements to the package list in the README file where they should appear more prominently than in the paragraph below the list. I am hesitant, though, to specify exact package names as these will differ between library versions and platforms. However, the current information should be sufficient for users familiar with the compilation of C++ code on Linux machines.
