### ISSUE TITLE
Option for overwriting files

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#82]
Currently, SoFiA will automatically and without notice overwrite any existing output files. It would be useful to include an additional option for explicitly allowing or disallowing the overwriting of files. The presence of such a parameter would also serve to make users more aware of the fact that existing output files might get overwritten.

**Comment by SoFiA-Admin** [comment]
A new option, `writeCat.overwrite`, has been added to SoFiA. It currently defaults to `true`, meaning that SoFiA will continue its previous default behaviour of automatically overwriting existing files. When set to `false`, SoFiA will now refuse to write any output products whose file name already exists and instead print an error message.

This new test has been implemented in `cubelets.py`, `writemask.py`, `store_ascii.py`, `store_xml.py` and `writemoment2.py`. It is **not** currently implemented in `addrel.py` and for all data products written as the result of the debugging flag being set to true. We will have to discuss whether this is the desired behaviour.

Another potential problem is that the check currently only occurs when the file is getting written, meaning that users may have to re-run the pipeline if they accidentally set the `writeCat.overwrite` parameter to `false`. An alternative solution would be to check at the start of the pipeline, but this is in principle impossible for some output files, e.g. spectra and cubelets, whose file names will only be known _after_ the pipeline has been completed.

**Comment by paoloserra** [comment]
I think that for the mask and moment images we should check before running the pipeline.

Cubelets etc are not a huge problem. A user could always rerun SoFiA with the latest mask, redo the merging and create the cubelets.

**Comment by SoFiA-Admin** [comment]
Thanks to Paolo, overwrite checks now occur at the beginning of the pipeline. This issue can now be closed.
