### ISSUE TITLE
Parallelisation of SoFiA

### ISSUE THREAD

**Issue by RussellJurek** [SoFiA-Admin/SoFiA#84]
Hi everyone,
          I've started this issue to begin the discussion of how to parallelise SoFiA.

The first thing that we need to determine is what kind of systems do we want to parallelise SoFiA for? Is their system solely CPUs or does it include GPUs? Is the memory uniform, distributed (called NUMA: Non-Uniform Memory Access) or a hybrid (also called NUMA)?

If their system is purely CPU based, then we can parallelise SoFiA using either OMP (Open Multi-Processing), MPI (Message Passing Interface) or a combination of the two. OMP is easier and quicker to code, avoids a lot of communication overheads, involves very little memory overheads and can be run on any system that supports threading (such as the posix model common to Unix). OMP is however limited to systems with uniform virtual memory and shared cache lines. MPI on the other hand can handle any arbitrary system. The system has to be prepared first however and be running a MPI daemon/service that essentially manages an ad hoc network of nodes/cores/threads.  For this reason a combination of MPI and OMP is usually used. MPI co-ordinates the nodes in a cluster, and each node uses OMP to co-ordinate its cores/threads. 

OMP and MPI behave differently and have different limitations, because they use different conceptual models of how to parallelise a program. OMP parallelises a program by generating threads or `forking' the program, and then collecting those threads after the the section of parallelised code has finished running. It remains a single program at all times during execution. MPI instead runs a suite of usually, but not necessarily, identical programs that talk to each other during execution.

Python doesn't support OMP, but it does support MPI. In combination with the uniform vs NUMA requirements of the two, it means that OMP parallelisation can only be implemented using Python modules written in C. MPI parralelisation can then be implemented at the pipeline level. This would quite naturally suit a system with a hybrid system. 

If their system includes GPUs, then we need to use either CUDA (Nvidia) or OpenCL (AMD + Nvidia) depending on the brand of their GPUs. In my experience CUDA offers better performance on Nvidia cards than OpenCL, but it's not enough to be a deal breaker. Both options are extensions of the C language. That means parallelising SoFiA to use GPUs involves writing python modules in C that use the CUDA/OpenCL extensions. Note that CUDA and OpenCL can both be nested inside a combination of OMP+MPI.

The limitations of OMP and MPI suggest the following parallelisation model for SoFiA. First, a data cube is divided up into sub-cubes that are processed by individual nodes. Each node is running its own SoFiA pipeline. These SoFiA pipelines then call Python modules written in C using OMP and CUDA/OpenCL. In this model a typical user with their laptop/desktop is a single node cluster, who will only benefit from the OMP (and CUDA/OpenCL)  parallelisation. Note that this will involve writing two separate versions of the SoFiA pipeline that do and don't run inside an MPI environment. Similarly, this will involve writing multiple versions of the Python modules in C, because not all compilers (Damn you Clang!!! Damn you to hell!) support OMP.

The changes that we make to SoFiA to allow multiple copies running on different cluster nodes to combine their results at the end, will also be beneficial for a typical user. These changes will allow them to process a datacube larger than their memory can hold, by processing it as a set of sub-cubes and combining the results at the end.

The object generating library is already well advanced in this regard. It can already process sub-cubes and stitch together the results at the end. The linker module needs to be extended to take advantage of this capability. Assuming this is the approach everyone wants to take to parallelise SoFiA.

Cheers,
Russell

**Comment by SoFiA-Admin** [comment]
Thanks a lot for the comprehensive overview! One quick comment on compilers: we currently require GCC for the compilation of SoFiA, which is the most commonly used compiler and a de-facto standard. It should therefore be safe to assume that GCC will be available on any system. I propose that we continue to explicitly support only GCC, so we don’t have to worry about the lack of OMP support in compilers such as Clang. (What I find most annoying about Clang is that fact that it disguises itself as GCC to trick people into using it!)

**Comment by RussellJurek** [comment]
Stefan Westerlund at ICRAR has already done a lot of work implementing source finders on distributed computer systems. He's published his work in PASA, 'A Framework for HI Spectral Source Finding Using Distributed-Memory Supercomputing'. It can be downloaded from here, http://de.arxiv.org/pdf/1407.4958 This is probably a good guide to how to implement the MPI portion of parallelising SoFiA.

**Comment by SoFiA-Admin** [comment]
From what it looks like, the plan at this point in time is to parallelise the new C version of SoFiA rather than the existing Python version. For that reason, we can close this issue and re-open new issues in the SoFiA 2 repository in the future to discuss parallelisation progress if necessary.
