### ISSUE TITLE
WCS conversion fails

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#87]
Another problem I noticed when running SoFiA on the test data cube (using the test parameter set provided with the cube, or any other parameter settings) is that conversion into WCS coordinates fails. The following messages are printed by the module:

    --- SoFiA: Adding WCS position to catalogue ---
    WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
    WARNING: FITSFixedWarning: 'spcfix' made the change 'Changed CTYPE3 from 'VELO-HEL' to 'VOPT', and SPECSYS to 'BARYCENT''. [astropy.wcs.wcs]
    WARNING: CELLSCAL keyword with value 1/F found.
    Will take into account varying pixel scale when calculating wcs coordinates.

In addition, the following **error message** appears:

    WARNING: WCS conversion of parameters failed.

As a result, no equatorial coordinates or velocities appear in the source catalogue. IAU-compliant source names don’t appear either, as they depend on the WCS information. Unfortunately, the error message is not particularly detailed, so it’s hard to see what is going wrong. A quick test revealed that `kvis` does display a coordinate grid and sky coordinates, so the correct information seems to be in the cube. I also ran SoFiA on a different data set, and WCS coordinates are calculated correctly in that case, so the problem must be somehow specific to the structure of the test data cube.

The first thing we will probably need to figure out is whether the problem is in the data cube or in SoFiA’s code. I will run a few more tests to shed light on this issue.

**Comment by bwinkel** [comment]
Which version of astropy do you use? I just tested the wcs module with version '1.1.dev11846' on the testcube and it works. Could be a bug with astropy.

Nevertheless, the header in the test cube does not conform to the WCS standard. As the warning tells, CTYPE3 is wrong, and there are several header elements missing (that are then silently put to defaults). While for most keyswords, this is fine, one should double check on this (e.g., is the specsys really 'BARYCENT'?). See WCS paper I-III for details.

**Comment by SoFiA-Admin** [comment]
Thanks for checking. My AstroPy version is 0.3+dfsg-3build1, which is presumably much older than yours (but still within our requirement of 0.2.5), so this could indeed have been an issue with AstroPy that got fixed in the meantime. Nevertheless, I would be keen to check the header of the cube against the FITS/WCS requirements to make sure that they conform to the standard. If not, we should update the header accordingly and the replace the current test data cube.

**Comment by RussellJurek** [comment]
It's possible that the older version of astropy doesn't have a bug, but
that the newer version has a new feature/s that handle improper FITS
headers.

**Comment by ngiese** [comment]
Could you please try the latest version? I added the speed of light constant in one of the wcs functions (add_wcs_coordinates), where it was used but not defined. Without it, it should not have worked, which is a bit strange. Maybe it fixes things for you.

**Comment by SoFiA-Admin** [comment]
Thanks a lot, excellent work, that fixed it! I will mark it as a SoFiA bug then and declare this issues closed. I wonder how the speed of light got lost in the first place...
