### ISSUE TITLE
GUI: View catalogue does not work with compression

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#88]
When compression is enabled in the output tab, the resulting catalogue (Analysis>View catalogue) can not be loaded. The error message is:
  Failed to load source catalogue:
  "name_of_the_xml_file_without_the_.gz_ending"
It is searching for a file which is not compressed. Could that be somehow changed without having to extract and save the resulting compressed catalogue?

**Comment by SoFiA-Admin** [comment]
In order for the catalogue viewing tool to be able to parse the XML catalogue, the data must be decompressed first, as the compressed data stream would not constitute a valid XML document. The easiest option would be to run `gunzip` before opening the file. Is there a particular reason for why we are compressing the catalogue files in the first place? This would not seem to be particularly useful, as the user would have to decompress the files anyway before viewing them. Compression would only appear to make sense for data cubes, which can be large in size.

**Comment by SoFiA-Admin** [comment]
This has been fixed, and the GUI now also displays compressed catalogues by using [zlib](http://www.zlib.net/) to decompress the file straight into memory (see d3fd339c4316774838f396c71dbf216bacf2be70). While this adds zlib to SoFiA’s installation requirements, this should be of little concern, as zlib is the de-facto standard compression library used by most software, including Linux, Python and indeed gzip itself, so we can expect it to be already installed on virtually every computer.
