### ISSUE TITLE
GUI output parameter warnings

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#89]
Some output parameter names seem to be outdated in the GUI parameter selection window, e.g. 'snr_min', 'snr_max' and 'snr_sum'. They have been removed at some point and you only get similar parameters if the parametrisation module is switched on. If the outdated parameters are selected in the GUI, there will be some warnings:

    WARNING: Skipping undefined parameter 'snr_min'.
    WARNING: Skipping undefined parameter 'snr_max'. 
    WARNING: Skipping undefined parameter 'snr_sum'.

The changes we make in parameter output are not always transparent for the user. Especially the need to enable the parametrisation in order to get any kind of flux measurement was also not clear to me.

**Comment by SoFiA-Admin** [comment]
Hm, this would seem like the intended behaviour. Whenever a parameter is not calculated, its output will necessarily be skipped, and a warning message will be printed instead. All of this happens in the pipeline, by the way, not in the GUI. The GUI only sets the `writeCat.parameters` parameter and offers a few possible entries to go into that parameter setting. From what I remember, the `snr_…` parameters are now only generated when the debugging flag is set, so in principle they could be removed from the GUI’s output parameter options altogether, as normal users won’t need them anyway.

Having to enable parameterisation to get source parameters would appear to be obvious, but I am happy to explicitly mention it again in a few places in the user manual and built-in help if this is a cause of confusion.

**Comment by SoFiA-Admin** [comment]
I changed the code as discussed above (see ae14228fda18d3dc378592aef2fd83f60bac7e88).

**Comment by SoFiA-Admin** [comment]
I think this can be closed now.
