### ISSUE TITLE
Controlling stride of RMS calculation from distribution of negative voxels

### ISSUE THREAD

**Issue by RussellJurek** [SoFiA-Admin/SoFiA#90]
Currently the stride of the RMS calculation from the distribution of the negative voxels is fixed to 3. Some basic testing has shown that while this returns a similar noise level to using a stride of 1, it is indeed different. This means that older versions of SoFiA produce different catalogs. It would be advantageous to enable users to edit the RMS stride calculation by editing the parameter file. This would be an advanced feature that users can't change from the GUI.

**Comment by paoloserra** [comment]
@RussellJurek Is this still relevant? Also, what is this "stride" thing???

**Comment by RussellJurek** [comment]
From memory it's not a big deal. Just a possible enhancement to give users more control. The stride is the spacing of the voxels used in the RMS calculation. Instead of fixing it to use every third voxel, we could give users the ability to specify the stride and a separate stride for each dimension.

**Comment by SoFiA-Admin** [comment]
The stride is now automatically determined such that at most a given number of pixels are used in the rms measurement to speed up the code. This issue can therefore be closed now.
