### ISSUE TITLE
QMAKESPEC instructions for installation

### ISSUE THREAD

**Issue by RussellJurek** [SoFiA-Admin/SoFiA#91]
I think it would be useful to add additional instructions to the README file for installation. These instructions would tell a user how to deal with a 'QMAKESPEC not found' error. This error prevents the GUI from being built, but is easily fixed by the user.

**Comment by SoFiA-Admin** [comment]
Good idea. I suggest to add that information to the Qt section of the [trouble shooting page](https://github.com/SoFiA-Admin/SoFiA/wiki/SoFiA-Troubleshooting) on the wiki. The README file already contains a link to that page, so the information should be easy to find.

**Comment by SoFiA-Admin** [comment]
I added help with the `QMAKESPEC` environment variable to the troubleshooting page, as discussed above. This issue can now be closed.
