### ISSUE TITLE
Format of RMS value in output table

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#93]
The current parameterisation module returns a measure of the local rms noise. This is included in the output table with format %.4f. I suggest to change it to %.2e. At the moment I'm working with a cube with noise ~0.2 mJy/beam, and the local noise at the location of individual sources is not reported with sufficient precision in the output table.

**Comment by RussellJurek** [comment]
I would prefer %.4e. That would preserve the precision, while allowing the range to dynamically adjust.

**Comment by SoFiA-Admin** [comment]
%.4e sounds good to me.

**Comment by paoloserra** [comment]
I have made the requested change in sofia_pipeline.py.

A more elegant solution would be to undo this change and have parametrisation.parametrise output the desired catParFormt . But for now this will do.
