### ISSUE TITLE
Change the default parameter file call?

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#96]
Currently we read the default parameter file within sofia_pipeline.py with:

default_file = '%s/SoFiA_default_input.txt'%(os.path.dirname(os.path.realpath(__file__)))

This does not work when submitting a SoFiA job to a supercomputer. The following works:

default_file = os.getenv('SOFIA_PIPELINE_PATH').replace('sofia_pipeline.py','SoFiA_default_input.txt')

I've already added the latter line to sofia_pipeline.py but it is currently commented out. Let me know whether you can see any reasons not to make this change.

**Comment by SoFiA-Admin** [comment]
I haven't tested this, but given that `sofia_pipeline.py` and `SoFiA_default_input.txt` reside in the same directory, this would seem a logical and elegant solution.

**Comment by paoloserra** [comment]
I've now implemented the change.
