### ISSUE TITLE
Incompatibility between processing of subcubes and production of "source products"

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#97]
When processing a subcube (whether as part of the optical finder or using the subcube selection outside the optical finder) individual source products (moment maps, cubelet, mask) are written incorrectly. The FITS files cannot be opened -- KVIS gives the error:
Insufficient data in file, need: 90 bytes, 0 remaining
foreign_guess_and_read: error reading FITS file

As a result, the pipeline is exited with exit code 1, and all following actions (including the writing of catalogues) are not performed. So this is a more general bug which is not related to the optical source finder. We will open a separate issue.

The SoFiA error looks like this:
  File "/Users/serra/Software/SoFiA-master/build/lib.macosx-10.5-intel-2.7/sofia/cubelets.py", line 187, in writeSubcube
    hdu.header['datamin']=np.nanmin(m0)
  File "/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/nanfunctions.py", line 218, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, keepdims=keepdims)
ValueError: zero-size array to reduction operation fmin which has no identity

**Comment by ngiese** [comment]
This behaviour is not very surprising because we never adjust the header information for the subcube anywhere. The cubelets module uses this header, thus gets the info for the full cube, but not the subcube. The CRPIX coordinates are critical here. I will fix this in the import_data.py module.

**Comment by paoloserra** [comment]
I wonder whether this is the reason why, for large cubes with CELLSCALE=1/F, the cubelet moment-0 images seem distorted. If we do not use the correct header information for the cubelets, then regridding would be done incorrectly.

**Comment by ngiese** [comment]
This problem would definitely also influence the regridding. The CRPIX values are updated properly in the cubelets module, however none of the NAXIS keywords (NAXIS3 is used in the regridding). I guess, the distortion in the moment-0 images is stronger with the subcubes option and also wrong, but not recognizable without the subcube option (because of the NAXIS3 keyword being wrong).

**Comment by paoloserra** [comment]
I found that, when importing subcubes, import_data was adjusting the header CRPIXi values but not the NAXISi values. This has now been fixed, and also the NAXISi values are now changed. I have also implemented a change of the NAXIS key to reflect the fact that we always discard the 4th axis, and deleted the 4th axis header keys.

**Comment by paoloserra** [comment]
The problem was caused by a transformation of the objects' XYZ coordinates and bounding boxes from the subcube to the full cube frame *before* extraction of the cubelets from the subcube. I have fixed this in https://github.com/SoFiA-Admin/SoFiA/commit/3aae9214ea02eded8f1c368d668bf9f60c96267d . Please test and let me know whether it fixes the problem for you.

**Comment by apopping** [comment]
I have tested the optical finder (which uses subcubes) and for every detection all the products are generated. As far as I can see the problem has been resolved so I am closing the issue!
