### ISSUE TITLE
Cubeletes are masked

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#98]
Cubelets created as part of the "source products" are already masked (in fact, they are zero-ed outside the mask). I thought the original idea was to provide unmasked cubelets, and that for this reason we provide the corresponding binary mask.

**Comment by ngiese** [comment]
This is weird. If I remember correctly, when I created the module the cubelets were not masked. Indeed the idea was to provide the unmasked cubelets and the corresponding masks. This should be changed accordingly. I could have a look at it.

**Comment by paoloserra** [comment]
Thanks!

**Comment by ngiese** [comment]
Sorry, I did not have time earlier to fix this. The problem was that the original cube was masked during the generation of the moment maps, which happens before the cubelets are made. I have fixed this by making a copy of the original cube in the writemask2 module before the cube is masked. Please test to see if this fixes your problem.

**Comment by SoFiA-Admin** [comment]
I've got a few questions about this:

1. Why does the original cube get masked during moment map generation? This would seem entirely unnecessary.
2. Is creating another copy of the cube problematic in terms of SoFiA’s memory footprint?
3. Should masking during moment map creation be unavoidable for some reason, could the order of tasks be changed such that moment maps are generated after the cubelets?

**Comment by SoFiA-Admin** [comment]
I will re-open this issue because the chosen solution may not be optimal yet.

**Comment by paoloserra** [comment]
@SoFiA-Admin , masking the original cube is necessary for regridding to work correctly (see https://github.com/SoFiA-Admin/SoFiA/issues/78 ). The point is that the detection mask cannot be used on the regridded cube because voxels in the mask do not correspond to voxels in the regridded cube. For this reason we mask first, then regrid, then make moment images.

After a short discussion, we have agreed to swap the order of cubelets and moment images generation. We will make cubelets first (using the original cube), then we will make the moment images (which includes masking the input cube). This solves the bug reported in this issue and avoids creating a copy of the input cube.

We will add a warning that the input cube in memory is now masked -- just in case anybody thinks of adding an additional module which uses the input cube after this step.

**Comment by ngiese** [comment]
Done.
