### ISSUE TITLE
SoFiA does not install with gsl 2.1

### ISSUE THREAD

**Issue by PeterKamphuis** [SoFiA-Admin/SoFiA#99]
We (Peter and Aditya) tried today to install SoFiA on an Ubuntu 16.04 system in which gsl 2.1 is installed. This resulted in the following error at installation.

src/parametrizer/BusyFit.cpp: In member function ‘int BusyFit::LMSolver()’:
src/parametrizer/BusyFit.cpp:547:24: error: ‘struct gsl_multifit_fdfsolver’ has no member named ‘J’
  gsl_multifit_covar(s->J, 0.0, covar);

Aditya fixed with the following modifications to BusyFit.cpp

Added new variable:

gsl_matrix       				  *J;

and replaced

gsl_multifit_covar(s->J, 0.0, covar);
with
gsl_multifit_fdfsolver_jac(s,J); 
gsl_multifit_covar(J, 0.0, covar); 

It would be great to hear from one of you that this is the right way of fixing this error and we hope that it also helps in the development of SoFiA.

Kind Regards,
Peter & Aditya

**Comment by RussellJurek** [comment]
Hi Peter,
       thanks for bringing this to our attention. I think we're going to have to review the changes log for gsl 2.1 before we can comment on this. Things like this are going to happen every now and then while using an external library. It can't avoided. 

Cheers,
Russell

**Comment by RussellJurek** [comment]
Assuming that this is the correct solution, we probably need to add a C/C++ preprocessor command that uses either the current code or Aditya's solution depending upon the GSL version number. It should be relatively straight forward. I'll make time to investigate this sometime in the next week.

**Comment by RussellJurek** [comment]
Hi Peter,
       I've finished going through the gsl v2.0 changelog and it's definitely due to a change they made to their library. Your students solution will *technically* work, but it's a very unstable solution. The missing element is that the array J needs to be allocated using the command gsl_matrix_alloc before it's used. Otherwise it's just pointing to a random location in heap memory. Ideally it would fail spectacularly so you know something went wrong. There's no guarantee though. It'll depend on your compiler and kernel. If it isn't failing spectacularly, then there's a good chance it's generating spurious covariance matrix results.

I've finished updating SoFiA to use both the v1.X and v2.X gsl libraries. I'm about to commit the change now. I've tested v1.16 and v2.1 of gsl with this new version. It compiled fine with both. Please give the new version a go and let me know how it went.

Cheers,
Russell

**Comment by PeterKamphuis** [comment]
Hi Russel,

Thank you for looking in to this. We'll let you know how the new version Fares.

Cheers,
Peter

**Comment by Punzo** [comment]
It solved for me: Ubuntu16.04; gsl 2.1; g++ 5.3.1. Davide.

**Comment by SoFiA-Admin** [comment]
This issue has been fixed and can be closed.
